import kfp
import os
import json

host = None
# the file is generated by `pipeline.py`, you could upload yaml or tar.gz
pipeline_file_path = "./pipeline.py.yaml"
pipeline_name = "testing9"
client = kfp.Client(host)


def create_pipeline():
    pipeline_file = os.path.join(pipeline_file_path)
    pipeline = client.upload_pipeline(pipeline_file, pipeline_name=pipeline_name)
    return pipeline


def list_pipelines():
    pipelines = client.list_pipelines()
    # print(ret)
    for p in pipelines.pipelines:
        print(p.id, p.name)

        print(get_pipeline(p.id))


def get_pipeline(id):
    return client.get_pipeline(id)


def run_pipeline():
    p = create_pipeline()
    e = client.get_experiment(experiment_name="demo")

    client.run_pipeline(experiment_id=e.id, job_name="test-sdk9", pipeline_id=p.id)


# create_pipeline()
# list_pipelines()
run_pipeline()
